services:

  postgres-db:
    image: postgres:16
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_DB=blog_db
      - POSTGRES_USER=blog_user
      - POSTGRES_PASSWORD=blog_password
      # DATABASE_URL=postgresql://blog_user:blog_password@localhost:5444/blog_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres-data:
