subscription CommentAdded($postId: ID!) {
  commentAdded(postId: $postId) {
    id
    content
    createdAt
    updatedAt
    isDeleted
    author {
      id
      username
      avatarUrl
    }
    post {
      id
      totalComments
    }
  }
}