subscription PostPublished {
  postPublished {
    id
    title
    slug
    excerpt
    status
    publishedAt
    createdAt
    author {
      ...AuthorBasic @mask_disable
      fullName
    }
    tags {
      ...TagInfo @mask_disable
    }
  }
}
