"""Add Post model with status slug and soft delete

Revision ID: 0600c4d74a4a
Revises: 6de1e04c1171
Create Date: 2025-08-26 16:40:05.450392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0600c4d74a4a'
down_revision: Union[str, Sequence[str], None] = '6de1e04c1171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type
    poststatus = sa.Enum('draft', 'published', 'archived', name='poststatus')
    poststatus.create(op.get_bind())
    
    op.add_column('posts', sa.Column('slug', sa.String(length=255), nullable=False))
    op.add_column('posts', sa.Column('excerpt', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('status', poststatus, nullable=False))
    op.add_column('posts', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('posts', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_posts_slug'), 'posts', ['slug'], unique=True)
    op.drop_constraint(op.f('posts_author_id_fkey'), 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_column('posts', 'published')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('posts_author_id_fkey'), 'posts', 'users', ['author_id'], ['id'])
    op.drop_index(op.f('ix_posts_slug'), table_name='posts')
    op.drop_column('posts', 'deleted_at')
    op.drop_column('posts', 'published_at')
    op.drop_column('posts', 'status')
    op.drop_column('posts', 'excerpt')
    op.drop_column('posts', 'slug')
    
    # Drop enum type
    poststatus = sa.Enum('draft', 'published', 'archived', name='poststatus')
    poststatus.drop(op.get_bind())
    # ### end Alembic commands ###
