"""Add comments table

Revision ID: fe19a2797a46
Revises: 0c5f07d7b470
Create Date: 2025-08-29 11:35:04.503737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe19a2797a46'
down_revision: Union[str, Sequence[str], None] = '0c5f07d7b470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Don't drop tags and post_tags tables - they are still in use
    # op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    # op.drop_table('tags')
    # op.drop_table('post_tags')
    
    # Add new columns to comments table
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('comments', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    
    # Update existing columns
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('comments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    
    # Drop old constraints and indices
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_constraint(op.f('comments_author_id_fkey'), 'comments', type_='foreignkey')
    op.drop_constraint(op.f('comments_post_id_fkey'), 'comments', type_='foreignkey')
    
    # Create new foreign keys with CASCADE
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    
    # Drop old column
    op.drop_column('comments', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_post_id_fkey'), 'comments', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(op.f('comments_author_id_fkey'), 'comments', 'users', ['author_id'], ['id'])
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.alter_column('comments', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('comments', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('comments', 'deleted_at')
    op.drop_column('comments', 'user_id')
    # Don't recreate tags and post_tags tables - they still exist
    # ### end Alembic commands ###
