query GetFollowingPosts($page: Int = 1, $limit: Int = 10) {
  followingPosts(page: $page, limit: $limit) {
    edges {
      node {
        ...PostCard @mask_disable
      }
    }
    pageInfo {
      ...PageInfoFields @mask_disable
    }
  }
}
