query GetMyPosts($page: Int = 1, $limit: Int = 10, $status: PostStatus) {
  myPosts(page: $page, limit: $limit, status: $status) {
    edges {
      node {
        ...PostCard @mask_disable
      }
    }
    pageInfo {
      ...PageInfoFields @mask_disable
    }
  }
}
