query GetMyFollowers {
  me {
    id
    username
    followers {
      ...AuthorDetailed @mask_disable
    }
    following {
      ...AuthorDetailed @mask_disable
    }
    followersCount
    followingCount
  }
}
