query GetPostsByTag($tagSlug: String!, $page: Int = 1, $limit: Int = 10) {
  postsByTag(tagSlug: $tagSlug, page: $page, limit: $limit) {
    edges {
      node {
        ...PostCard @mask_disable
      }
    }
    pageInfo {
      ...PageInfoFields @mask_disable
    }
  }
}
