query GetPostsByTags($tagSlugs: [String!]!, $requireAll: Boolean = false, $page: Int = 1, $limit: Int = 10) {
  postsByTags(tagSlugs: $tagSlugs, requireAll: $requireAll, page: $page, limit: $limit) {
    edges {
      node {
        ...PostCard @mask_disable
      }
    }
    pageInfo {
      ...PageInfoFields @mask_disable
    }
  }
}
