query GetPosts($page: Int = 1, $limit: Int = 10, $search: String) {
  posts(page: $page, limit: $limit, search: $search) {
    edges {
      node {
        ...PostCard @mask_disable
      }
    }
    pageInfo {
      ...PageInfoFields @mask_disable
    }
  }
}
