query GetPost($id: ID, $slug: String) {
  post(id: $id, slug: $slug) {
    id
    title
    slug
    content
    excerpt
    status
    createdAt
    updatedAt
    publishedAt
    author {
      ...AuthorDetailed @mask_disable
    }
    tags {
      ...TagInfo @mask_disable
    }
    comments(limit: 50) {
      ...CommentInfo @mask_disable
    }
    totalComments
    likesCount
    isLiked
  }
}
