query GetUserProfile($username: String!) {
  user(username: $username) {
    id
    username
    fullName
    bio
    avatarUrl
    followersCount
    followingCount
    isFollowedByMe
    createdAt
  }
}
